import {
  PayCircleOutlined,
  ShoppingCartOutlined,
  MessageOutlined,
  TeamOutlined,
  UserOutlined,
  DashboardOutlined,
  ApiOutlined,
  CameraOutlined,
  EditOutlined,
  CodeOutlined,
  LineOutlined,
  BarChartOutlined,
  AreaChartOutlined,
  ClusterOutlined,
  ToolOutlined,
  LaptopOutlined,
  DisconnectOutlined,
  UsbOutlined,
  InsertRowLeftOutlined,
  BranchesOutlined,
  ProjectOutlined,
  FundViewOutlined,
  DesktopOutlined,
  AlertOutlined,
  ProfileOutlined,
  HomeOutlined,
  GlobalOutlined,
  AppstoreOutlined,
  MonitorOutlined,
  DatabaseOutlined,
  SettingOutlined,
} from '@ant-design/icons'
import { 
  Analysis,
  SettingConfig,
  Data, 
} from '@icon-park/react';

export default {
  'pay-circle-o': <PayCircleOutlined />,
  'shopping-cart': <ShoppingCartOutlined />,
  'camera-o': <CameraOutlined />,
  'line-chart': <LineOutlined />,
  'code-o': <CodeOutlined />,
  'area-chart': <AreaChartOutlined />,
  'bar-chart': <BarChartOutlined />,
  'ClusterOut-icon': <ClusterOutlined />, //设备管理器
  'ToolOutlined': <ToolOutlined />,  // 系统管理
  "ProjectOutlined":<ProjectOutlined />,//审计
  "FundViewOutlined":<FundViewOutlined />, // 系统检测
  'BranchesOutlined':<BranchesOutlined />,
  'InsertRowLeftOutlined':<InsertRowLeftOutlined />,
  'UsbOutlined':<UsbOutlined />,
  'LaptopOutlined': <LaptopOutlined />,
  'message': <MessageOutlined />,
  'team': <TeamOutlined />,
  'dashboard': <DashboardOutlined />,
  'user': <UserOutlined />,
  'api': <ApiOutlined />,
  'edit': <EditOutlined />,
  'DesktopOutlined':<DesktopOutlined/>,
  'AlertOutlined':<AlertOutlined />,
  "ProfileOutlined":<ProfileOutlined />,
  "HomeOutlined":<HomeOutlined />,
  'DatabaseOutlined':<DatabaseOutlined />,
  "GlobalOutlined":<GlobalOutlined />,
  "AppstoreOutlined":<AppstoreOutlined />,
  "SettingOutlined":<SettingOutlined />,
  "MonitorOutlined":<MonitorOutlined/>,
  "Analysis":<span className='anticon anticon-global'><Analysis theme='outline'/></span>,
  "SettingConfig":<span className='anticon anticon-global'><SettingConfig theme='outline' /></span>,
  "Data":<span className='anticon anticon-global'><Data theme='outline' /></span>,
}